### ISSUE TITLE
User Story: <Title>

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#15]
As a user, I want to be able to create an account so that I can have my address saved for future purchases.

Acceptance Criteria

Acceptance Criteria 1
Given that I am a registered user When I open the website The Login button is clearly visible on the navigation bar.
Acceptance Criteria 1
Given that I am a registered user who is not signed in When I try to leave a review I am prompted to log in.
Acceptance Criteria 1
Given that I am a currently logged-in user When I am on any page on the website a clear Logout button is displayed on the navigation bar.

**Tasks**
- [ ] Task 1 - Install Allauth package.
- [ ] Task 2 - Add middleware and other settings from the Allauth documentation.
- [ ] Task 3 - Copy the Allauth templates into main templates folder.

**Epic: #7**
