### ISSUE TITLE
User Story: Login and Logout. Epic: #7

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#16]
As a **user**, I want to be able to **log in and out of my account** so that I can **access my profile**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that I am a registered user **When** I open the website **Then** Login button is clearly visible on the navigation bar.
- Acceptance Criteria 2
  - **Given** that I am a registered user **When** I open the website **Then** Logout button is clearly visible on the navigation bar.

**Tasks**
- [x] Task 1 - Design login/logout buttons on the navigation bar.
- [x] Task 2 - Connect logout button.
- [x] Task 3 - Connect login button.

**Epic: #7**
