### ISSUE TITLE
User Story: Responsive Design and Accessibility. Epic #9

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#19]
As a **user**, I want **to be able to view the site on any device I choose** so that I can **shop on the go**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given that I am user** that **is browsing the site on mobile** the **all pages look good on my device**

**Tasks**
- [x] Task 1 - Design responsive header and navigation bar.
- [x] Task 2 - Design a responsive footer bar.
- [x] Task 3 - Design responsive index page.

**Epic: #9**
