### ISSUE TITLE
User Story: Set-up vsCode. Epic #1

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#2]
As a **developer**, I can **use local IDE** so that **I can start developing my program**.

**Acceptance Criteria**
- Acceptance Criteria 1 - Connect the vsCode and set up with the project.
- Acceptance Criteria 1 - The vsCode should only install packages needed for this project.

**Tasks**
- [x] Task 1 - Clone repository from GitHub to vsCode.
- [x] Task 2 - Create a virtual environment to install only project-related packages.
- [x] Task 3 - Install Django.
- [x] Task 4 - Create an env.py file and hide the secret key in there.
- [x] Task 5 - Create requirements.txt file
- [x] Task 6 - Create Hereku Procfile.

**Epic: #1**
