### ISSUE TITLE
User Story: View product details. Epic: #8

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#21]
As a **user**, I want to **be able to view the details of a product** so that **I can decide if I want to purchase it**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that the user is on the product listing page,
  **When**  the user clicks anywhere on the product card, 
  **Then** the user should be directed to a product details page displaying comprehensive information about the selected product.
- Acceptance Criteria 2 
  - **Given** that the user is on the product details page,
  **When** the page loads,
  **Then** the user should be able to view key details such as product name, description, price, specifications, add to favourites and any other relevant information necessary for making a purchase decision.

**Tasks**
- [x] Task 1 - Design responsive product details page.
- [x] Task 2 - Add a button to add the product to my bag.
- [x] Task 3 - Add a button to add the product to my favourite products.
- [x] Task 4 - Add an option to go back to the previous page. 

**Epic: #8**
