### ISSUE TITLE
User Story: Edit Bag quantity. Epic: #10 

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#23]
As a **user**, I want to be able to **edit the quantity of a product in my shopping bag** so that **I can purchase the quantity I want**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that the user is viewing their shopping bag,
  **When** they attempt to edit the quantity of a product,
  **Then** the system should allow them to change the quantity successfully.

- Acceptance Criteria 2 
- **Given**  that the user is on the product or product detail page,
  **When** they try to add a product to their bag,
  **Then** there should be an option to edit the quantity before adding it to the bag.

- Acceptance Criteria 3 
- **Given** that the user is on the checkout page,
  **When** they review their selected products,
  **Then** there should be an option to edit the quantity for each product in the shopping bag.

**Tasks**
- [x] Task 1 - Add an option to edit the quantity to be added to the bag on the product and product detail page.
- [x] Task 2 - Add an option to edit quantity on the checkout page.
- [x] Task 3 - Block users entering negative values.

**Epic: #10**
