### ISSUE TITLE
User Story: Delete Product from the Bag. Epic: #10

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#24]
As a **user**, I want to be able to **delete a product from my shopping bag** so that I can **remove it if I change my mind**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that the user is on the shopping bag page,
  **When** they select a product and choose to remove it,
  **Then** the system should successfully remove the selected product from the shopping bag.

- Acceptance Criteria 2 
  - **Given** that the user is on the checkout page,
  **When** they review their selected products,
  **Then** there should be an option to remove a product from the shopping bag.

- Acceptance Criteria 3 
  - **Given** that the user has removed a product from the shopping bag,
  **When** they view the updated shopping bag,
  **Then** the removed product should no longer be visible in the bag.

**Tasks**
- [x] Task 1 - Add an option to remove the product from the bag.
- [x] Task 2 - Add an option to remove the product on the checkout page.
- [x]  Task 3 - Add an option to update the quantity of a product in the shopping bag.

**Epic: #10**
