### ISSUE TITLE
User Story: View Bag. Epic: #10

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#25]
As a **user**, I want to be able to **view my shopping bag** so that I can **see the total cost of my purchase**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that the user is on any page of the website,
  **When** they click on the "Shopping Bag" link,
  **Then** the system should navigate them to a page displaying the contents of their shopping bag.

- Acceptance Criteria 2 
  - **Given** that the user has added products to their shopping bag,
  **When** they view their shopping bag,
  **Then** The system should display a list of the added products along with their quantities and individual prices.

- Acceptance Criteria 3 
  - **Given** that the user is on the shopping bag page,
  **When** they view the page,
  **Then** the system should calculate and display the total cost of the items in their shopping bag.

**Tasks**
- [x] Task 1 - Add a visible on all pages shopping bag link on the top of the page.
- [x] Task 2 - Display the list of added products on the shopping bag page.
- [x] Task 3 - Calculate and display the total cost on the shopping bag page.
- [x]  Task 4 - Create responsive shopping pag page

**Epic: #10**
