### ISSUE TITLE
User Story: Order History. Epic: #11

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#26]
As a **user**, I want to be able to **view my order history** so that I can **see what I have purchased in the past**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that the user is logged in
  **When** they navigate to their profile page
  **Then** they should see a container displaying their previous order history.

- Acceptance Criteria 2 
  - **Given**  that the user is not logged in
  **When** they navigate to their profile page
  **Then** the order history container should not be visible.

**Tasks**
- [x] Task 1 - Create a container on the user profile page with their previous order history.
- [x] Task 2 - Make this only visible for Authenticated users.
- [x] Task 3 -  Implement the logic to fetch and display order history details.

**Epic: #11**
