### ISSUE TITLE
User Story: User Address CRUD. Epic: #11

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#27]
As a **user**, I want to be able to **add or edit my billing and shipping information** so that I can **easily checkout**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that the user is authenticated,
  - **When** they go to their profile page,
  - **Then** they should see a container displaying at least two of their saved addresses, including both billing and shipping information.
  
- Acceptance Criteria 2 
  - **Given** that the user is authenticated,
  - **When** they navigate to the profile page and view their addresses,
  - **Then** they should have an option to edit the existing addresses.
  
- Acceptance Criteria 3 
  - **Given** that the user is authenticated,
  - **When** they navigate to the profile page and view their addresses,
  - **Then** they should have the option to add new addresses, including both billing and shipping information.
  

**Tasks**
- [x] Task 1 - Add a container on the user profile page with 2 of the user's addresses.
- [x] Task 2 - Create an option to edit addresses.
- [x] Task 3 - Create an option to add addresses.
- [x] Task 4 - Create an option to remove addresses.

**Epic: #11**
