### ISSUE TITLE
User Story: Favorites. Epic: #11

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#28]
As a **user**, I want to be able to **add a product to the favourites list** so that I can **purchase it later**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that the user is authenticated,
  - **When** they navigate to a product page,
  - **Then** they should see an option/button to add the product to their favourites list.
  
- Acceptance Criteria 2 
  - **Given** that the user is authenticated,
  - **When** they go to their profile page,
  - **Then** they should see a section/container displaying their favourite products.
  
- Acceptance Criteria 3 
  - **Given** that the user is authenticated,
  - **When**  they are on the user profile page and view their favourite products,
  - **Then** they should be able to delete specific products from their favourites list.

**Tasks**
- [x] Task 1 - Add an option for authenticated user to add the product to their favourite product list on all the product pages.
- [x] Task 2 - Add a favourite product container on the user profile page.
- [x] Task 3 - Add an option for a user to delete favourite products.

**Epic: #11**
