### ISSUE TITLE
User Story: Product Review. Epic: #12

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#29]
As a **user**, I want to be able to **leave a review for a product** so that I can **share my experience with other users**.

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that the user is logged in and navigates to the product details page
  **When** they scroll or explore the page
  **Then** they should see an option to leave a review for the product.

- Acceptance Criteria 2 
  - **Given** that the user is the author or an admin
  **When**  they view the product details page
  **Then** they should have an option to remove reviews.

- Acceptance Criteria 3 
  - **Given** that the user has left reviews for the product
  **When** they view the product details page
  **Then** they should see a list of their reviews for that product.

**Tasks**
- [ ] Task 1 - On the product details page create an option for authenticated users to leave a review.
- [ ] Task 2 - Create an option for the author or admin to remove the reviews.
- [ ] Task 3 - Create a list on the product details page with the user's reviews if they exist.

**Epic: #12**
