### ISSUE TITLE
User Story: Initial deployment to Heroku. Epic: #1

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#3]
As a **developer,** I can **deploy the website skeleton to Heroku** so that **I can make sure all initial settings are correct**

**Acceptance Criteria**
- Acceptance Criteria 1 - The project needs to be set up with all the correct settings and files,
- Acceptance Criteria 1 - Has to be connected to GitHub for easy deployment.

**Tasks**
- [x] Task 1 - Create Procfile as per Heroku instructions.
- [x] Task 2 - Create requirements.txt file.
- [x] Task 3 - Add config vars in Heroku project settings.
- [x] Task 4 - Connect the Heroku app with the GitHub repository.

**Epic: #1**
