### ISSUE TITLE
User Story: SEO. Epic: #13

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#35]
As a **developer** I can **create SEO and other marketing strategies** so that **this website could be found by more people**

**Acceptance Criteria**
- Acceptance Criteria 1 
  - **Given** that **When** the **Then**
- Acceptance Criteria 2 
  - **Given** that **When** the **Then**
- Acceptance Criteria 3 
  - **Given** that **When** the **Then**

**Tasks**
- [x] Task 1 - Add a robots.txt file
- [x] Task 2 - add a sitemap.xml file
- [x] Task 3 - add descriptive meta tags in the HTML.
- [x] Task 4 - Create a Facebook business page.
- [x] Task 5 - Create a Mailchimp newsletter signup on the footer.

**Epic: #13**
