### ISSUE TITLE
User Story: Wireframes. Epic: #1

### ISSUE THREAD

**Issue by Inc21** [Inc21/velotronix-PP5#4]
As a **developer** I can **create wireframes** so that **I will have precise blueprints when designing a website**

**Tasks**
- [x] Task 1 - Create a Home page wireframe. Also, including the mobile version.
- [x] Task 2 - Create a wireframe for a list of products page. Also, including the mobile version.
- [x] Task 3 - Create a wireframe for a single product page. Also, including the mobile version.

**Epic: #1**
